version = 0.1

[default.deploy.parameters]
stack_name = "ride-the-bus-api"
resolve_s3 = true
s3_prefix = "ride-the-bus-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
